name: "git-metrics report in pull request"
description: "A GitHub action to report metrics in pull request"
author: "Jeremie Drouet <jeremie.drouet@gmail.com>"

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: "bar-chart"
  color: "blue"

# Define your inputs here.
inputs:
  comment_tag:
    description: "Tag to use for later updates"
    required: false
    default: "git-metrics"

runs:
  using: composite
  steps:
    - name: output git-metrics
      shell: bash
      id: diff
      run: |
        echo "metrics<<EOF" >> $GITHUB_OUTPUT
        git-metrics diff origin/$GITHUB_BASE_REF..HEAD >> $GITHUB_OUTPUT
        echo EOF >> $GITHUB_OUTPUT

    - name: commenting pull request
      uses: thollander/actions-comment-pull-request@v2
      with:
        comment_tag: ${{ inputs.comment_tag }}
        message: |
          📈 This is how your metrics evolved 📉

          ```
          ${{ steps.diff.outputs.metrics }}
          ```
